### ISSUE TITLE
Bug: `alt+enter` does not work when using compatibility mode

### ISSUE THREAD

**Issue by chrisgrieser** [alfredapp/alfred-gallery-workflow#1]
If you are using Alfred Compatibility Mode, `alt+enter` requires "don't close Alfred window on actioning" to work properly.

![Pasted image 2023-07-10 at 23 13 27@2x](https://github.com/alfredapp/alfred-gallery-workflow/assets/73286100/59ffb60a-9eeb-4e79-9ca0-ca52fcc9e5e1)

**Comment by vitorgalvao** [comment]
Updated. Thank you.
